### PR TITLE
#310 fix rune anvil tooltip position

### LINKED ISSUE #310: Tooltips misplaced in rune anvil at default windowed resolution
Image

### PR DESCRIPTION
**Pull request by immortius**
Tweaks display of the right tooltip in the rune anvil so it doesn't flick across to the left side of the screen.

Ultimately should have a better solution for the before/after information (tooltips are tricky to control) but suggest waiting for feedback on the rune anvil to be reviewed.

Closes #310

### CODE REVIEW

File: src/main/java/com/wanderersoftherift/wotr/gui/screen/RuneAnvilScreen.java [hunk 1]
```diff
@@ -40,6 +50,11 @@ public RuneAnvilScreen(RuneAnvilMenu menu, Inventory playerInventory, Component
     protected void init() {
         super.init();
 
+        fullDisplay = minecraft.screen.width > imageWidth + 2 * TOOLTIP_WIDTH_HINT + 4 * TOOLTIP_BORDER;
+        if (!fullDisplay) {
+            leftPos = Math.max(16, minecraft.screen.width - imageWidth - TOOLTIP_WIDTH_HINT - TOOLTIP_BORDER) / 2;
```
Comment (ImplementsLegend) [inline src/main/java/com/wanderersoftherift/wotr/gui/screen/RuneAnvilScreen.java]: I think it looks better like this:
```suggestion
            leftPos = Math.max(16, minecraft.screen.width - imageWidth - TOOLTIP_WIDTH_HINT - TOOLTIP_BORDER*2);
```

**Review by ImplementsLegend — APPROVED** [review]
